/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_lederui_developmenttest_data_BCRInterface */

#ifndef _Included_com_example_lederui_developmenttest_dataBCRInterface
#define _Included_com_example_lederui_developmenttest_dataBCRInterface
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_lederui_developmenttest_data_BCRInterface
 * Method:    BCRInit
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_example_lederui_developmenttest_data_BCRInterface_BCRInit
  (JNIEnv *, jclass);

/*
 * Class:     com_example_lederui_developmenttest_data_BCRInterface
 * Method:    BCRClose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_lederui_developmenttest_data_BCRInterface_BCRClose
  (JNIEnv *, jclass);

/*
 * Class:     com_example_lederui_developmenttest_data_BCRInterface
 * Method:    BCRStartScan
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_example_lederui_developmenttest_data_BCRInterface_BCRStartScan
  (JNIEnv *, jclass);

/*
 * Class:     com_example_lederui_developmenttest_data_BCRInterface
 * Method:    BCRStopScan
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_example_lederui_developmenttest_data_BCRInterface_BCRStopScan
  (JNIEnv *, jclass);

/*
 * Class:     com_example_lederui_developmenttest_data_BCRInterface
 * Method:    BCRScanIsComplete
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_example_lederui_developmenttest_data_BCRInterface_BCRScanIsComplete
  (JNIEnv *, jclass);

/*
 * Class:     com_example_lederui_developmenttest_data_BCRInterface
 * Method:    BCRIsReady
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_example_lederui_developmenttest_data_BCRInterface_BCRIsReady
  (JNIEnv *, jclass);

/*
 * Class:     com_example_lederui_developmenttest_data_BCRInterface
 * Method:    BCRGetTicketInfo
 * Signature: ([BI)I
 */
JNIEXPORT jint JNICALL Java_com_example_lederui_developmenttest_data_BCRInterface_BCRGetTicketInfo
  (JNIEnv *, jclass , jbyteArray , jint);

/*
 * Class:     com_example_lederui_developmenttest_data_BCRInterface
 * Method:    BCRGetHWInfomation
 * Signature: ([BI)Z
 */
JNIEXPORT jboolean JNICALL Java_com_example_lederui_developmenttest_data_BCRInterface_BCRGetHWInformation
  (JNIEnv *, jclass, jbyteArray , jint);

/*
 * Class:     com_example_lederui_developmenttest_data_BCRInterface
 * Method:    BCRBeep
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_example_lederui_developmenttest_data_BCRInterface_BCRBeep
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_example_lederui_developmenttest_data_BCRInterface
 * Method:    BCRUserLEDOff
 * Signature: ()Z
 */
JNIEXPORT void JNICALL Java_com_example_lederui_developmenttest_data_BCRInterface_BCRUserLEDOff
  (JNIEnv *, jclass);

/*
 * Class:     com_example_lederui_developmenttest_data_BCRInterface
 * Method:    BCRUserLEDOn
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_example_lederui_developmenttest_data_BCRInterface_BCRUserLEDOn
        (JNIEnv *, jclass, jint);

/*
 * Class:     com_example_lederui_developmenttest_data_BCRInterface
 * Method:    BCRAimOff
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_example_lederui_developmenttest_data_BCRInterface_BCRAimOff
  (JNIEnv *, jclass);

/*
 * Class:     com_example_lederui_developmenttest_data_BCRInterface
 * Method:    BCRAimOn
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_example_lederui_developmenttest_data_BCRInterface_BCRAimOn
  (JNIEnv *, jclass);

/*
 * Class:     com_example_lederui_developmenttest_data_BCRInterface
 * Method:    BCRSetScanMode
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_example_lederui_developmenttest_data_BCRInterface_BCRSetScanMode
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_example_lederui_developmenttest_data_BCRInterface
 * Method:    BCRGetScanMode
 * Signature: (Ljava/lang/Integer;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_example_lederui_developmenttest_data_BCRInterface_BCRGetScanMode
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_example_lederui_developmenttest_data_BCRInterface
 * Method:    BCRGetTriggerStatus
 * Signature: (Ljava/lang/Integer;)V
 */
JNIEXPORT void JNICALL Java_com_example_lederui_developmenttest_data_BCRInterface_BCRGetTriggerStatus
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_example_lederui_developmenttest_data_BCRInterface
 * Method:    BCRGetScanDpi
 * Signature: (Ljava/lang/Integer;Ljava/lang/Integer;)V
 */
JNIEXPORT void JNICALL Java_com_example_lederui_developmenttest_data_BCRInterface_BCRGetScanDpi
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     com_example_lederui_developmenttest_data_BCRInterface
 * Method:    BCRGetImageSize
 * Signature: (Ljava/lang/Integer;Ljava/lang/Integer;Ljava/lang/Integer;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_example_lederui_developmenttest_data_BCRInterface_BCRGetImageSize
  (JNIEnv *, jclass, jobject, jobject, jobject);

/*
 * Class:     com_example_lederui_developmenttest_data_BCRInterface
 * Method:    BCREnableBeep
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_lederui_developmenttest_data_BCRInterface_BCREnableBeep
  (JNIEnv *, jclass);

/*
 * Class:     com_example_lederui_developmenttest_data_BCRInterface
 * Method:    BCRDisableBeep
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_lederui_developmenttest_data_BCRInterface_BCRDisableBeep
  (JNIEnv *, jclass);

/*
 * Class:     com_example_lederui_developmenttest_data_BCRInterface
 * Method:    BCRClearBuffer
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_lederui_developmenttest_data_BCRInterface_BCRClearBuffer
  (JNIEnv *, jclass);

/*
 * Class:     com_example_lederui_developmenttest_data_BCRInterface
 * Method:    BCRGetSWVersion
 * Signature: ([BI)V
 */
JNIEXPORT jstring JNICALL Java_com_example_lederui_developmenttest_data_BCRInterface_BCRGetSWVersion
  (JNIEnv *, jclass);

/*
 * Class:     com_example_lederui_developmenttest_data_BCRInterface
 * Method:    BCRGetImage
 * Signature: ([BI)I
 */
JNIEXPORT jint JNICALL Java_com_example_lederui_developmenttest_data_BCRInterface_BCRGetImage
  (JNIEnv *, jclass, jbyteArray , jobject);

/*
 * Class:     com_example_lederui_developmenttest_data_BCRInterface
 * Method:    BCRResetComm
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_example_lederui_developmenttest_data_BCRInterface_BCRResetComm
  (JNIEnv *, jclass);

/*
 * Class:     com_example_lederui_developmenttest_data_BCRInterface
 * Method:    BCRWakeup
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_example_lederui_developmenttest_data_BCRInterface_BCRWakeup
  (JNIEnv *, jclass);

/*
 * Class:     com_example_lederui_developmenttest_data_BCRInterface
 * Method:    BCRSleep
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_example_lederui_developmenttest_data_BCRInterface_BCRSleep
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_example_lederui_developmenttest_data_BCRInterface
 * Method:    BCRDisableCode
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_example_lederui_developmenttest_data_BCRInterface_BCRDisableCode
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_example_lederui_developmenttest_data_BCRInterface
 * Method:    BCREnableCode
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_example_lederui_developmenttest_data_BCRInterface_BCREnableCode
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_example_lederui_developmenttest_data_BCRInterface
 * Method:    BCRDisable
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_example_lederui_developmenttest_data_BCRInterface_BCRDisable
  (JNIEnv *, jclass);

/*
 * Class:     com_example_lederui_developmenttest_data_BCRInterface
 * Method:    BCREnable
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_example_lederui_developmenttest_data_BCRInterface_BCREnable
  (JNIEnv *, jclass);

/*
 * Class:     com_example_lederui_developmenttest_data_BCRInterface
 * Method:    BCRQueryCapability
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_example_lederui_developmenttest_data_BCRInterface_BCRQueryCapability
  (JNIEnv *, jclass);

/*
 * Class:     com_example_lederui_developmenttest_data_BCRInterface
 * Method:    BCRGetLastErrorStr
 * Signature: ([BI)V
 */
JNIEXPORT jstring JNICALL Java_com_example_lederui_developmenttest_data_BCRInterface_BCRGetLastErrorStr
  (JNIEnv *, jclass);

/*
 * Class:     com_example_lederui_developmenttest_data_BCRInterface
 * Method:    BCRGetLastErrorCode
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_example_lederui_developmenttest_data_BCRInterface_BCRGetLastErrorCode
  (JNIEnv *, jclass);


/*
 * Class:     com_example_lederui_developmenttest_data_BCRInterface
 * Method:    BCRGetDataLength
 * Signature: (Ljava/lang/Integer;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_example_lederui_developmenttest_data_BCRInterface_BCRGetDataLength
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
