/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_lederui_developmenttest_data_ScannerInterface */

#ifndef _Included_com_example_lederui_developmenttest_data_ScannerInterface
#define _Included_com_example_lederui_developmenttest_data_ScannerInterface
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_lederui_developmenttest_data_ScannerInterface
 * Method:    SInit
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_example_lederui_developmenttest_data_ScannerInterface_SInit
  (JNIEnv *, jclass);

/*
 * Class:     com_example_lederui_developmenttest_data_ScannerInterface
 * Method:    SQueryCapability
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_example_lederui_developmenttest_data_ScannerInterface_SQueryCapability
  (JNIEnv *, jclass);

/*
 * Class:     com_example_lederui_developmenttest_data_ScannerInterface
 * Method:    SGetScanDpi
 * Signature: (Ljava/lang/Integer;Ljava/lang/Integer;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_example_lederui_developmenttest_data_ScannerInterface_SGetScanDpi
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     com_example_lederui_developmenttest_data_ScannerInterface
 * Method:    SGetBrandDpi
 * Signature: (Ljava/lang/Integer;Ljava/lang/Integer;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_example_lederui_developmenttest_data_ScannerInterface_SGetBrandDpi
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     com_example_lederui_developmenttest_data_ScannerInterface
 * Method:    SGetHWInformation
 * Signature: ([BI)Z
 */
JNIEXPORT jboolean JNICALL Java_com_example_lederui_developmenttest_data_ScannerInterface_SGetHWInformation
  (JNIEnv *, jclass, jbyteArray, jint);

/*
 * Class:     com_example_lederui_developmenttest_data_ScannerInterface
 * Method:    SGetSWVersion
 * Signature: ([BI)Z
 */
JNIEXPORT jboolean JNICALL Java_com_example_lederui_developmenttest_data_ScannerInterface_SGetSWVersion
  (JNIEnv *, jclass, jbyteArray, jint);

/*
 * Class:     com_example_lederui_developmenttest_data_ScannerInterface
 * Method:    SGetLastErrorCode
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_example_lederui_developmenttest_data_ScannerInterface_SGetLastErrorCode
  (JNIEnv *, jclass);

/*
 * Class:     com_example_lederui_developmenttest_data_ScannerInterface
 * Method:    SGetLastErrorStr
 * Signature: ([BI)V
 */
JNIEXPORT jstring JNICALL Java_com_example_lederui_developmenttest_data_ScannerInterface_SGetLastErrorStr
  (JNIEnv *, jclass, jbyteArray, jint);

/*
 * Class:     com_example_lederui_developmenttest_data_ScannerInterface
 * Method:    SStart
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_example_lederui_developmenttest_data_ScannerInterface_SStart
  (JNIEnv *, jclass);

/*
 * Class:     com_example_lederui_developmenttest_data_ScannerInterface
 * Method:    SStop
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_example_lederui_developmenttest_data_ScannerInterface_SStop
  (JNIEnv *, jclass);

/*
 * Class:     com_example_lederui_developmenttest_data_ScannerInterface
 * Method:    ScanIsComplete
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_example_lederui_developmenttest_data_ScannerInterface_ScanIsComplete
  (JNIEnv *, jclass);

/*
 * Class:     com_example_lederui_developmenttest_data_ScannerInterface
 * Method:    ScannerIsReady
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_example_lederui_developmenttest_data_ScannerInterface_ScannerIsReady
  (JNIEnv *, jclass);

/*
 * Class:     com_example_lederui_developmenttest_data_ScannerInterface
 * Method:    SGetOriginImageSize
 * Signature: (Ljava/lang/Integer;Ljava/lang/Integer;Ljava/lang/Integer;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_example_lederui_developmenttest_data_ScannerInterface_SGetOriginImageSize
  (JNIEnv *, jclass, jobject, jobject, jobject);

/*
 * Class:     com_example_lederui_developmenttest_data_ScannerInterface
 * Method:    SGetOriginImage
 * Signature: ([BLjava/lang/Integer;)I
 */
JNIEXPORT jint JNICALL Java_com_example_lederui_developmenttest_data_ScannerInterface_SGetOriginImage
  (JNIEnv *, jclass, jbyteArray, jobject);

/*
 * Class:     com_example_lederui_developmenttest_data_ScannerInterface
 * Method:    SGetTicketInfo
 * Signature: ([BLjava/lang/Integer;)I
 */
JNIEXPORT jint JNICALL Java_com_example_lederui_developmenttest_data_ScannerInterface_SGetTicketInfo
  (JNIEnv *, jclass, jbyteArray, jobject);

/*
 * Class:     com_example_lederui_developmenttest_data_ScannerInterface
 * Method:    SPrintBrandImage
 * Signature: ([BIII)I
 */
JNIEXPORT jint JNICALL Java_com_example_lederui_developmenttest_data_ScannerInterface_SPrintBrandImage
  (JNIEnv *, jclass, jbyteArray, jint, jint, jint);

/*
 * Class:     com_example_lederui_developmenttest_data_ScannerInterface
 * Method:    SRollBack
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_example_lederui_developmenttest_data_ScannerInterface_SRollBack
  (JNIEnv *, jclass);

/*
 * Class:     com_example_lederui_developmenttest_data_ScannerInterface
 * Method:    SRecognizeItem
 * Signature: (IIII[B[B)Z
 */
JNIEXPORT jboolean JNICALL Java_com_example_lederui_developmenttest_data_ScannerInterface_SRecognizeItem
  (JNIEnv *, jclass, jint, jint, jint, jint, jbyteArray, jbyteArray);

/*
 * Class:     com_example_lederui_developmenttest_data_ScannerInterface
 * Method:    SAdjustSensibility
 * Signature: (Ljava/lang/Integer;Ljava/lang/Integer;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_example_lederui_developmenttest_data_ScannerInterface_SAdjustSensibility
  (JNIEnv *, jclass, jobject, jobject);

JNIEXPORT jint JNICALL Java_com_example_lederui_developmenttest_data_ScannerInterface_SPrintSelfDefBrandImage
        (JNIEnv *, jclass ,jbyteArray, jint x, jint y);

#ifdef __cplusplus
}
#endif
#endif
