/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_lederui_developmenttest_fragment_PrinterFragment */

#ifndef _Included_com_example_lederui_developmenttest_fragment_PrinterFragment
#define _Included_com_example_lederui_developmenttest_fragment_PrinterFragment
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_lederui_developmenttest_fragment_PrinterFragment
 * Method:    PrintInit
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jboolean JNICALL Java_com_example_lederui_developmenttest_fragment_PrinterFragment_PrintInit
  (JNIEnv *, jobject);

/*
 * Class:     com_example_lederui_developmenttest_fragment_PrinterFragment
 * Method:    SetCutMode
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jboolean JNICALL Java_com_example_lederui_developmenttest_fragment_PrinterFragment_SetCutMode
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_example_lederui_developmenttest_fragment_PrinterFragment
 * Method:    SetAllcutOrHalfcut
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_example_lederui_developmenttest_fragment_PrinterFragment_SetAllcutOrHalfcut
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_example_lederui_developmenttest_fragment_PrinterFragment
 * Method:    PrintSample
 * Signature: (I)I
 */
JNIEXPORT jboolean JNICALL Java_com_example_lederui_developmenttest_fragment_PrinterFragment_PrintSample
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_example_lederui_developmenttest_fragment_PrinterFragment
 * Method:    PrintAllString
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jboolean JNICALL Java_com_example_lederui_developmenttest_fragment_PrinterFragment_PrintAllString
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_example_lederui_developmenttest_fragment_PrinterFragment
 * Method:    PrintImage
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jboolean JNICALL Java_com_example_lederui_developmenttest_fragment_PrinterFragment_PrintImage
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_example_lederui_developmenttest_fragment_PrinterFragment
 * Method:    PrintBlackBarcode
 * Signature: (II)Ljava/lang/String;
 */
JNIEXPORT bool JNICALL Java_com_example_lederui_developmenttest_fragment_PrinterFragment_PrintBlackBarcode
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_example_lederui_developmenttest_fragment_PrinterFragment
 * Method:    PrintCodePaper
 * Signature: (II)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_lederui_developmenttest_fragment_PrinterFragment_PrintCodePaper
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_example_lederui_developmenttest_fragment_PrinterFragment
 * Method:    PrintContinue
 * Signature: (II)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_lederui_developmenttest_fragment_PrinterFragment_PrintContinue
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_example_lederui_developmenttest_fragment_PrinterFragment
 * Method:    PrintPaperMode
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT bool JNICALL Java_com_example_lederui_developmenttest_fragment_PrinterFragment_PrintPaperMode
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_example_lederui_developmenttest_fragment_PrinterFragment
 * Method:    PrintSpeedTest
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_lederui_developmenttest_fragment_PrinterFragment_PrintSpeedTest
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_example_lederui_developmenttest_fragment_PrinterFragment
 * Method:    PrintCutPaperSpeed
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_lederui_developmenttest_fragment_PrinterFragment_PrintCutPaperSpeed
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_example_lederui_developmenttest_fragment_PrinterFragment
 * Method:    PrintBarCode
 * Signature: (II)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_lederui_developmenttest_fragment_PrinterFragment_PrintBarCode
  (JNIEnv *, jobject, jint, jint);


JNIEXPORT jstring JNICALL Java_com_example_lederui_developmenttest_fragment_PrinterFragment_GetLastErrStr
        (JNIEnv *, jobject);

JNIEXPORT bool JNICALL Java_com_example_lederui_developmenttest_fragment_PrinterFragment_PrintString
        (JNIEnv *, jobject , jstring);

#ifdef __cplusplus
}
#endif
#endif
